language: csharp
mono: none
dotnet: 2.1

install:
- dotnet restore

script:
 - dotnet build -c Release
 - dotnet test -c Release tests/TianLaLu.Extensions.Tests/TianLaLu.Extensions.Tests.csproj

deploy:
  skip_cleanup: true
  provider: script
  script: dotnet pack -c Release && dotnet nuget push src/TianLaLu.Extensions/bin/Release/TianLaLu.*.nupkg --api-key $NUGET_API_KEY
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^(\d+\.)?(\d+\.)?(\*|\d+)$