language: csharp
mono: none
dotnet: 2.1.403

install:
- dotnet restore

script:
 - dotnet build
 - dotnet test tests/TianLaLu.Extensions.Tests/TianLaLu.Extensions.Tests.csproj
 - dotnet pack -c Release

deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push src/TianLaLu.Extensions/bin/Release/TianLaLu.*.nupkg --api-key $NUGET_API_KEY
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^(\d+\.)?(\d+\.)?(\*|\d+)$