version: 0.1.{build}
os: Visual Studio 2017
image: Visual Studio 2017
clone_depth: 1
skip_tags: true
configuration: Release
platform: Any CPU
cache: '%USERPROFILE%\.nuget\packages'

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  SONAR_TOKEN:
    secure: pmiRXtPrqm/FvtqmbAm7nrZE+UGPTqQkEH6jRWeYHQguGPUYgP+hdqKN/y3RCo0Z

branches:
  only:
  - master

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

artifacts:
 - path: .\**\TianLaLu.*.nupkg
   name: NuGet

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

init:
 # Good practise, because Windows line endings are different from Unix/Linux ones
 - cmd: git config --global core.autocrlf true

install:
 - cmd: dotnet --version
 - cmd: dotnet add .\tests\TianLaLu.Extensions.Tests\TianLaLu.Extensions.Tests.csproj package Appveyor.TestLogger

before_build:
 - cmd: appveyor-retry dotnet restore -v Minimal
 - cmd: dotnet tool install --global dotnet-sonarscanner
 - cmd: dotnet sonarscanner begin /k:"tianlalu-extensions-core" /d:sonar.organization="tianlalu-team" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="%SONAR_TOKEN%" /d:sonar.cs.opencover.reportsPaths=".\tests\TianLaLu.Extensions.Tests\coverage.opencover.xml" /d:sonar.coverage.exclusions="**Tests*.cs" /v:"%appveyor_build_version%"

build_script:
 - cmd: dotnet build -c %CONFIGURATION% --no-restore

after_build:
 - cmd: dotnet pack -c %CONFIGURATION% --no-build

test_script:
 - cmd: dotnet test .\tests\TianLaLu.Extensions.Tests\TianLaLu.Extensions.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_test:
 - cmd: dotnet sonarscanner end /d:sonar.login="%SONAR_TOKEN%"

deploy:
  provider: NuGet
  name: production
  api_key:
    secure: cVM2YoFj7BZNZHxbK4Cdz+1REd05i/FRleiEpxfF9LlZEWHiZffg2xIqEeYGdviu
  skip_symbols: true
