version: 0.1.{build}
os: Visual Studio 2017
image: Visual Studio 2017
clone_depth: 1
skip_tags: true
configuration: Release
platform: Any CPU
cache: '%USERPROFILE%\.nuget\packages'

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: true

branches:
  only:
  - master

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

artifacts:
 - path: .\artifacts\**\*.nupkg
   name: NuGet

init:
 # Good practise, because Windows line endings are different from Unix/Linux ones
 - cmd: git config --global core.autocrlf true
 - ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

install:
 - cmd: dotnet --version
# - cmd: dotnet restore -v Minimal
 - cmd: dotnet add .\tests\TianLaLu.Extensions.Tests\TianLaLu.Extensions.Tests.csproj package Appveyor.TestLogger

before_build:
 - cmd: appveyor-retry dotnet restore -v Minimal

build_script:
 - cmd: dotnet build -c %CONFIGURATION% --version-suffix %LABEL%

after_build:
 - cmd: dotnet pack -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts

test_script:
 - cmd: dotnet test .\tests\TianLaLu.Extensions.Tests\TianLaLu.Extensions.Tests.csproj --logger:trx;LogFileName=result.trx

after_test:
 - ps: $wc = New-Object 'System.Net.WebClient'
 - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests\TianLaLu.Extensions.Tests\TestREsults\result.trx))

deploy: off
